<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" 
       xmlns:xacro="http://ros.org/wiki/xacro"
        
	name="first">

<xacro:include filename="$(find robomuse)/urdf/robomuse_rack/rack.gazebo.xacro"/> 
<xacro:include filename="$(find robomuse)/urdf/robomuse_base/base.gazebo.xacro"/> 
 <xacro:include filename="$(find robomuse)/urdf/robomuse_base/base.transmission.xacro"/>
  <xacro:include filename="$(find robomuse)/urdf/youbot_gazebo.urdf.xacro"/>
  <xacro:include filename="$(find robomuse)/urdf/youbot_properties.urdf.xacro"/>

<xacro:property name="kinect_cam_py" value="0"/>


  <property name="rack_base_size_x" value=".484"/>
  <property name="rack_base_size_y" value="0.200"/>
  <property name="rack_base_size_z" value="0.006"/>
  <property name="rack_base_mass" value="2.0"/>

  <property name="vertical_offset_x" value="0.242"/>
  <property name="vertical_offset_y" value="0.1"/>
  <property name="vertical_offset_z" value="0.003"/>
  <property name="rack_vertical_mass" value="0.1"/>

  <property name="rack_vertical_size_x" value="0.0254"/>
  <property name="rack_vertical_size_y" value="0.0254"/>
  <property name="rack_vertical_size_z" value="0.780"/>

  <property name="base_size_x" value="1.6936"/>
  <property name="base_size_y" value="1.2008"/>
  <property name="base_size_z" value="0.005"/>
  <property name="base_mass" value="22.0"/>

  <property name="caster_offset_x" value="0.27907"/>
  <property name="caster_offset_y" value="0.2"/>
  <property name="caster_offset_z" value="0"/>
  <property name="caster_mass" value="0.1"/>

  <property name="wheel_offset_x" value="0.0"/>
  <property name="wheel_offset_y" value="0.0"/>
  <property name="wheel_offset_z" value="0.0"/>

  <property name="wheel_mass" value="0.4"/>
  <property name="wheel_radius" value="0.05"/>
  <property name="wheel_length" value="0.005"/>

  <property name="caster_joint_damping" value="1.0"/>
  <property name="caster_joint_friction" value="1.0"/>
  <property name="caster_joint_effort" value="30"/>
  <property name="caster_joint_velocity" value="10"/>
  <property name="caster_joint_safety_k_velocity" value="10.0"/>

  <property name="wheel_joint_damping" value="1.0"/>
  <property name="wheel_joint_friction" value="1.0"/>
  <property name="wheel_joint_effort" value="30"/>
  <property name="wheel_joint_velocity" value="10"/>
  <property name="wheel_joint_safety_k_velocity" value="10.0"/>

    <!--link name="base_footprint">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
        <material name="Red"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-base_size_z / 2.0}" rpy="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <child link="base_link"/>
      <parent link="base_footprint"/>
    </joint-->

   
<link name="base_link">
      <inertial>
        <mass value="22"/>
        <origin xyz="0 0 0.3"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0.3" rpy="0 0 0"/>
                <geometry>
  			<mesh filename="package://robomuse/meshes/basenew.dae" />	
        	</geometry>
        	<material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.3" rpy="0 0 0"/>
        	<geometry>
         		<mesh filename="package://robomuse/meshes/basenew.dae" />
        	</geometry>
      </collision>
    </link>
      <joint name="chassis_joint_base" type="fixed">
      <origin xyz="0 .68 ${-0.26}" rpy="0 0 0"/>
      <child link="chassis_link"/>
      <parent link="base_link"/>
    </joint>
    <link name="chassis_link">
      <inertial>
        <mass value="22"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="3.14 0 0"/>
                <geometry>
  			<mesh filename="package://robomuse/meshes/chassis.dae" />	
        	</geometry>
        	<material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="3.14 0 0"/>
        	<geometry>
         		<mesh filename="package://robomuse/meshes/chassis.dae" />
        	</geometry>
      </collision>
    </link>
        <joint name="caster_joint_fl" type="continuous">
      <origin xyz="${-caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="${caster_joint_effort}" velocity="${caster_joint_velocity}"/>
      <dynamics damping="${caster_joint_damping}" friction="${caster_joint_friction}"/>
      <safety_controller k_velocity="${caster_joint_safety_k_velocity}"/>
      <parent link="base_link"/>
      <child link="caster_link_fl"/>
    </joint>
    <link name="caster_link_fl">
      <inertial>
        <mass value="${caster_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
    </link>

    <joint name="wheel_joint_fl" type="continuous">
      <axis xyz="0 1 0"/>
      <limit effort="${wheel_joint_effort}" velocity="${wheel_joint_velocity}"/>
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
      <parent link="caster_link_fl"/>
      <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
      <safety_controller k_velocity="${wheel_joint_safety_k_velocity}"/>
      <child link="wheel_link_fl"/>
    </joint>
    <link name="wheel_link_fl">
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
	      <!--mesh filename="package://youbot_description/meshes/youbot_base/front-left_wheel.dae" /-->
          <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
<!--fr-->
	    <joint name="caster_joint_fr" type="continuous">
      <origin xyz="${caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="${caster_joint_effort}" velocity="${caster_joint_velocity}"/>
      <dynamics damping="${caster_joint_damping}" friction="${caster_joint_friction}"/>
      <safety_controller k_velocity="${caster_joint_safety_k_velocity}"/>
      <parent link="base_link"/>
      <child link="caster_link_fr"/>
    </joint>
    <link name="caster_link_fr">
      <inertial>
        <mass value="${caster_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
    </link>

    <joint name="wheel_joint_fr" type="continuous">
      <axis xyz="0 1 0"/>
      <limit effort="${wheel_joint_effort}" velocity="${wheel_joint_velocity}"/>
      <dynamics damping="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
      <safety_controller k_velocity="${wheel_joint_safety_k_velocity}"/>
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
      <parent link="caster_link_fr"/>
      <child link="wheel_link_fr"/>
    </joint>
    <link name="wheel_link_fr">
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <!--mesh filename="package://youbot_description/meshes/youbot_base/front-right_wheel.dae" /-->
          <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
<!--caster-->
    <joint name="caster_joint" type="continuous">
      <origin xyz="0 ${caster_offset_y} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="${caster_joint_effort}" velocity="${caster_joint_velocity}"/>
      <dynamics damping="${caster_joint_damping}" friction="${caster_joint_friction}"/>
      <safety_controller k_velocity="${caster_joint_safety_k_velocity}"/>
      <parent link="base_link"/>
      <child link="caster_link"/>
    </joint>
   
    <link name="caster_link">
      <inertial>
        <mass value="${caster_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
    </link>

    <joint name="wheel_joint" type="continuous">
      <axis xyz="1 1 0"/>
      <limit effort="${wheel_joint_effort}" velocity="${wheel_joint_velocity}"/>
      <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
      <parent link="caster_link"/>
      <dynamics damping ="${wheel_joint_damping}" friction="${wheel_joint_friction}"/>
      <safety_controller k_velocity="${wheel_joint_safety_k_velocity}"/>
      <child link="wheel_link"/>
    </joint>
   
    <link name="wheel_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
	      <!--mesh filename="package://youbot_description/meshes/youbot_base/front-left_wheel.dae" /-->
          <sphere radius="${wheel_radius/4*3}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <sphere radius="${wheel_radius/4*3}"/>
        </geometry>
      </collision>
    </link>

      <joint name="rack_joint_base" type="fixed">
      <origin xyz="${vertical_offset_x} ${vertical_offset_y - .20} 0" rpy="0 0 0"/>
      <child link="rack_vertical_link1"/>
      <parent link="base_link"/>
    </joint>

    <link name="rack_vertical_link1">
      <inertial>
        <mass value=".2"/>
        <origin xyz="${rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="${-rack_vertical_size_x/2} ${-rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="${-rack_vertical_size_x/2} ${-rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
      </collision>
    </link>

<joint name="rack_joint_base1" type="fixed">
      <origin xyz="${vertical_offset_x} ${-vertical_offset_y - .20} 0" rpy="0 0 0"/>
      <child link="rack_vertical_link2"/>
      <parent link="base_link"/>
    </joint>

<link name="rack_vertical_link2">
      <inertial>
        <mass value=".2"/>
        <origin xyz="${rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="${-rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="${-rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
      </collision>
    </link>
<joint name="rack_joint_base2" type="fixed">
      <origin xyz="${-vertical_offset_x} ${-vertical_offset_y - .20} 0" rpy="0 0 0"/>
      <child link="rack_vertical_link3"/>
      <parent link="base_link"/>
    </joint>
<link name="rack_vertical_link3">
      <inertial>
        <mass value=".2"/>
        <origin xyz="${rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="${rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="${rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
      </collision>
    </link>
<joint name="rack_joint_base3" type="fixed">
      <origin xyz="${-vertical_offset_x} ${vertical_offset_y - .20} 0" rpy="0 0 0"/>
      <child link="rack_vertical_link4"/>
      <parent link="base_link"/>
    </joint>
<link name="rack_vertical_link4">
      <inertial>
        <mass value=".2"/>
        <origin xyz="${rack_vertical_size_x/2} ${rack_vertical_size_y/2} ${rack_vertical_size_z/2}"/>
        <inertia ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983" iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943"/>
      </inertial>
      <visual>
        <origin xyz="${rack_vertical_size_x/2} ${-rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
        <material name="Orange"/>
      </visual>
      <collision>
        <origin xyz="${rack_vertical_size_x/2} ${-rack_vertical_size_y/2} ${rack_vertical_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_vertical_size_x} ${rack_vertical_size_y} ${rack_vertical_size_z}"/>
        </geometry>
      </collision>
    </link>

<joint name="rack_joint_link11" type="fixed">
      <origin xyz="${vertical_offset_x} ${vertical_offset_y} 0.090" rpy="0 0 0"/>
      <child link="rack_link2"/>
      <parent link="rack_vertical_link1"/>
    </joint>
<link name="rack_link2">
      <inertial>
        <mass value="1"/>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.09"/>
        <inertia ixx="0.00774243378" ixy="-0.01404395602" ixz="-.00042131868" iyy="0.04530596321" iyz="0.00017409863" izz="0.05303446911"/>
      </inertial>
      <visual>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.09" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.09" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
      </collision>
</link>

<joint name="rack_joint_link21" type="fixed">
      <origin xyz="${vertical_offset_x} ${vertical_offset_y} 0.190" rpy="0 0 0"/>
      <child link="rack_link3"/>
      <parent link="rack_vertical_link1"/>
    </joint>
<link name="rack_link3">
      <inertial>
        <mass value="1"/>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.19"/>
        <inertia ixx="0.00774243378" ixy="-0.01404395602" ixz="-.00042131868" iyy="0.04530596321" iyz="0.00017409863" izz="0.05303446911"/>
      </inertial>
      <visual>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.19" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.19" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
      </collision>
</link>
<joint name="rack_joint_link31" type="fixed">
      <origin xyz="${vertical_offset_x} ${vertical_offset_y} 0.290" rpy="0 0 0"/>
      <child link="rack_link4"/>
      <parent link="rack_vertical_link1"/>
    </joint>
<link name="rack_link4">
      <inertial>
        <mass value="1"/>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.29"/>
        <inertia ixx="0.00774243378" ixy="-0.01404395602" ixz="-.00042131868" iyy="0.04530596321" iyz="0.00017409863" izz="0.05303446911"/>      </inertial>
      <visual>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.29" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.29" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
      </collision>
</link>
<joint name="rack_joint_link41" type="fixed">
      <origin xyz="${vertical_offset_x} ${vertical_offset_y} 0.390" rpy="0 0 0"/>
      <child link="rack_link5"/>
      <parent link="rack_vertical_link1"/>
    </joint>
<link name="rack_link5">
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0.39"/>
        <inertia ixx="0.00774243378" ixy="-0.01404395602" ixz="-.00042131868" iyy="0.04530596321" iyz="0.00017409863" izz="0.05303446911"/>      </inertial>
      <visual>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.39" rpy="0 0 0"/>
                <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="${-rack_base_size_x} ${-rack_base_size_y} 0.39" rpy="0 0 0"/>
        <geometry>
          <box size="${rack_base_size_x} ${rack_base_size_y} ${rack_base_size_z}"/>
        </geometry>
      </collision>
</link>
   

 <joint name="camera_rgb_joint" type="fixed">
      <origin xyz="0 0.3 0.1" rpy="0 0 ${M_PI/2} "/>
      <parent link="base_link"/>
      <child link="camera_rgb_frame" />
    </joint>
    <link name="camera_rgb_frame"/>

    <joint name="camera_rgb_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_rgb_frame" />
      <child link="camera_rgb_optical_frame" />
    </joint>
    <link name="camera_rgb_optical_frame"/>

    <joint name="camera_joint" type="fixed">
      <origin xyz="-0.031 ${-kinect_cam_py} -0.016" rpy="0 0 0"/>
      <parent link="camera_rgb_frame"/>
      <child link="camera_link"/>
    </joint>  
      <link name="camera_link">
      <visual>
       <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
        <geometry>
         <mesh filename="package://robomuse/meshes/kinect.dae"/>
        </geometry>
      </visual>
  	  <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  	    <geometry>
  	      <box size="0.07271 0.27794 0.073"/>
  	    </geometry>
  	  </collision>
      <inertial>
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
                 iyy="0.000498940" iyz="0.0"
                 izz="0.003879257" />
      </inertial>
    </link>

    <!-- The fixed joints & links below are usually published by static_transformers launched by the OpenNi launch 
         files. However, for Gazebo simulation we need them, so we add them here.
         (Hence, don't publish them additionally!) -->
	<joint name="camera_depth_joint" type="fixed">
	  <origin xyz="0 ${2 * -kinect_cam_py} 0" rpy="0 0 0" />
	  <parent link="camera_rgb_frame" />
	  <child link="camera_depth_frame" />
	</joint>
	<link name="camera_depth_frame"/>

	<joint name="camera_depth_optical_joint" type="fixed">
	  <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
	  <parent link="camera_depth_frame" />
	  <child link="camera_depth_optical_frame" />
	</joint>
	<link name="camera_depth_optical_frame"/>
	
	<!-- Kinect sensor for simulation -->
<xacro:kinect_sim_3dsensor/>
<xacro:rack_gazebo/>
<xacro:base_gazebo/>
<xacro:robomuse_base_transmission/>   

</robot>
